Ext.define('Bloodbankapp.bloodbankapp.shared.com.model.bloodbankboundedcontext.bloodbank.BloodRequestModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "bloodRequestId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "noOfUnits",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "patientName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "requestedByDoctor",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "requestedByHospital",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dateNeededBy",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "dispatchedToPatientOn",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "bldg",
          "reference": "BloodGroup",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});