Ext.define('Bloodbankapp.bloodbankapp.shared.com.model.bloodbankboundedcontext.bloodbank.ClinicalInfoModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "clinicalInfoId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "height",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "weight",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "pulse",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bp",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "temprature",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "unitsOfBlood",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "DonorVisit",
          "reference": "DonorVisitModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});