Ext.define('Bloodbankapp.bloodbankapp.shared.com.model.bloodbankboundedcontext.bloodbank.TestBloodModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "collectedDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "expiryDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "isTested",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "noOfUnits",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "donorVisitId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "donor",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }]
});