DROP TABLE IF EXISTS `ast_BloodResult_T`;

CREATE TABLE `ast_BloodResult_T` ( `bloodResultId` VARCHAR(256) NOT NULL, `collectedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `expiryDate` TIMESTAMP NULL, `isTested` TINYINT(1) NOT NULL DEFAULT '1', `noOfUnits` INT(10) NOT NULL, `donorVisitId` VARCHAR(256) NOT NULL, `donor` VARCHAR(256) NULL DEFAULT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(10) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(10) NULL DEFAULT NULL, PRIMARY KEY (`bloodResultId`));

