DROP TABLE IF EXISTS `ast_RegisterADonor_T`;

CREATE TABLE `ast_RegisterADonor_T` ( `donorId` VARCHAR(256) NOT NULL, `donorName` VARCHAR(256) NOT NULL, `dob` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `phoneNo` VARCHAR(256) NOT NULL, `emailId` VARCHAR(256) NOT NULL, `lastDonationDate` TIMESTAMP NULL, `howOftenUDonated` INT(10) NOT NULL, `gendr` VARCHAR(64) NOT NULL, `bg` VARCHAR(256) NOT NULL, `addr` VARCHAR(64) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(10) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(10) NULL DEFAULT NULL, PRIMARY KEY (`donorId`));

